config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lodgements
  resources :deposits
  resources :withdraws
  resources :bankaccounts
  

root 'bankaccounts#index'

end

app/models/bankaccount.rb
class Bankaccount < ActiveRecord::Base
	has_many :deposits
	has_many :withdraws
	has_many :lodgements
belongs_to :user
end

app/controllers/bankaccounts_controller.rb
class BankaccountsController < ApplicationController
  before_action :set_bankaccount, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!
  # GET /bankaccounts
  # GET /bankaccounts.json
  def index
    @bankaccounts = Bankaccount.all
  end

  # GET /bankaccounts/1
  # GET /bankaccounts/1.json
  def show
  end

  # GET /bankaccounts/new
  def new
    @bankaccount = current_user.bankaccounts.build
  end

  # GET /bankaccounts/1/edit
  def edit
  end

  # POST /bankaccounts
  # POST /bankaccounts.json
  def create
    @bankaccount = current_user.bankaccounts.build(bankaccount_params)

    respond_to do |format|
      if @bankaccount.save
        format.html { redirect_to @bankaccount, notice: 'Bankaccount was successfully created.' }
        format.json { render :show, status: :created, location: @bankaccount }
      else
        format.html { render :new }
        format.json { render json: @bankaccount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bankaccounts/1
  # PATCH/PUT /bankaccounts/1.json
  def update
    respond_to do |format|
      if @bankaccount.update(bankaccount_params)
        format.html { redirect_to @bankaccount, notice: 'Bankaccount was successfully updated.' }
        format.json { render :show, status: :ok, location: @bankaccount }
      else
        format.html { render :edit }
        format.json { render json: @bankaccount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bankaccounts/1
  # DELETE /bankaccounts/1.json
  def destroy
    @bankaccount.destroy
    respond_to do |format|
      format.html { redirect_to bankaccounts_url, notice: 'Bankaccount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bankaccount
      @bankaccount = Bankaccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bankaccount_params
      params.require(:bankaccount).permit(:image_url, :name, :amount, :sort_code)
    end
end

app/helpers/bankaccounts_helper.rb
module BankaccountsHelper
end

app/views/bankaccounts/_form.html.erb
<%= form_for @bankaccount, :html => { :class => "form-horizontal bankaccount" } do |f| %>

    <% if @bankaccount.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@bankaccount.errors.count, "error") %> prohibited this bankaccount from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @bankaccount.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_url, :class => 'form-control' %>
    </div>
    <%= error_span(@bankaccount[:image_url]) %>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@bankaccount[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@bankaccount[:amount]) %>
  </div>
  <div class="control-group">
    <%= f.label :sort_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sort_code, :class => 'form-control' %>
    </div>
    <%= error_span(@bankaccount[:sort_code]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            bankaccounts_path, :class => 'btn btn-default' %>

<% end %>

app/views/bankaccounts/edit.html.erb
<%- model_class = Bankaccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bankaccounts/index.html.erb
<%- model_class = Bankaccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:image_url) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:sort_code) %></th>
      
 <th><%= model_class.human_attribute_name(:email) %></th>
<th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bankaccounts.each do |bankaccount| %>
     
 <tr>       

<%if bankaccount.user == current_user || bankaccount.user_id == 3%> 
 <td><%= link_to bankaccount.id, bankaccount_path(bankaccount) %></td>
<td>
        <div class="image">
            <%= link_to (image_tag bankaccount.image_url, :style => "height:100px; width:100px"), bankaccount %>
        </div>
    </td>


       
        <!--<td><%= bankaccount.image_url %></td>-->
        <td><%= bankaccount.name %></td>
        <td><%= bankaccount.amount %></td>
        <td><%= bankaccount.sort_code %></td>
        <td><%= bankaccount.user.email %></td>

<td><%=l bankaccount.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bankaccount_path(bankaccount), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bankaccount_path(bankaccount),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
<%end%>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bankaccount_path,
            :class => 'btn btn-primary' %>

app/views/bankaccounts/new.html.erb
<%- model_class = Bankaccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bankaccounts/show.html.erb
<%- model_class = Bankaccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image_url) %>:</strong></dt>
  <dd><%= @bankaccount.image_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bankaccount.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @bankaccount.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sort_code) %>:</strong></dt>
  <dd><%= @bankaccount.sort_code %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bankaccounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bankaccount_path(@bankaccount), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bankaccount_path(@bankaccount),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>