config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lodgements
  resources :deposits
  resources :withdraws
  resources :bankaccounts
  

root 'bankaccounts#index'

end

app/models/lodgement.rb
class Lodgement < ActiveRecord::Base
belongs_to :bankaccount
belongs_to :user
end

app/controllers/lodgements_controller.rb
class LodgementsController < ApplicationController
  before_action :set_lodgement, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!

  # GET /lodgements
  # GET /lodgements.json
  def index
    @lodgements = Lodgement.all
  end

  # GET /lodgements/1
  # GET /lodgements/1.json
  def show
  end

  # GET /lodgements/new
  def new
    @lodgement = current_user.lodgements.build
  end

  # GET /lodgements/1/edit
  def edit
  end

  # POST /lodgements
  # POST /lodgements.json
  def create
    @lodgement = current_user.lodgements.build(lodgement_params)

 

@acc = Bankaccount.find(@lodgement.name)
    @acc.amount += @lodgement.amount
    @lodge.balance -= @lodgement.amount	    

@lodgement.save
@acc.save
    puts @acc.amount
    puts @lodgement.balance


 respond_to do |format|
      if @lodgement.save
        format.html { redirect_to @lodgement, notice: 'Lodgement was successfully created.' }
        format.json { render :show, status: :created, location: @lodgement }
      else
        format.html { render :new }
        format.json { render json: @lodgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lodgements/1
  # PATCH/PUT /lodgements/1.json
  def update
    respond_to do |format|
      if @lodgement.update(lodgement_params)
        format.html { redirect_to @lodgement, notice: 'Lodgement was successfully updated.' }
        format.json { render :show, status: :ok, location: @lodgement }
      else
        format.html { render :edit }
        format.json { render json: @lodgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lodgements/1
  # DELETE /lodgements/1.json
  def destroy
    @lodgement.destroy
    respond_to do |format|
      format.html { redirect_to lodgements_url, notice: 'Lodgement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lodgement
      @lodgement = Lodgement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lodgement_params
      params.require(:lodgement).permit(:name, :amount, :description)
    end
end

app/helpers/lodgements_helper.rb
module LodgementsHelper
end

app/views/lodgements/_form.html.erb
<%= form_for @lodgement, :html => { :class => "form-horizontal lodgement" } do |f| %>

    <% if @lodgement.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lodgement.errors.count, "error") %> prohibited this lodgement from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lodgement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@lodgement[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@lodgement[:amount]) %>
  </div>
 <div class="control-group">
    <%= f.label :balance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :balance, :class => 'form-control' %>
    </div>
    <%= error_span(@lodgement[:amount]) %>
  </div>
  



<div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@lodgement[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            lodgements_path, :class => 'btn btn-default' %>

<% end %>

app/views/lodgements/edit.html.erb
<%- model_class = Lodgement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lodgements/index.html.erb
<%- model_class = Lodgement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      

<th><%= model_class.human_attribute_name(:balance) %></th>
<th><%= model_class.human_attribute_name(:description) %></th>
<th><%= model_class.human_attribute_name(:email) %></th>
      
<th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lodgements.each do |lodgement| %>
<%if lodgement.user == current_user %>      

<tr>
        <td><%= link_to lodgement.id, lodgement_path(lodgement) %></td>
        <td><%= lodgement.name %></td>
        <td><%= lodgement.amount %></td>
        

<td><%= lodgement.balance %></td>
<td><%= lodgement.description %></td>
<td><%= lodgement.user.email %></td>        
<td><%=l lodgement.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lodgement_path(lodgement), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lodgement_path(lodgement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lodgement_path,
            :class => 'btn btn-primary' %>

app/views/lodgements/new.html.erb
<%- model_class = Lodgement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lodgements/show.html.erb
<%- model_class = Lodgement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @lodgement.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @lodgement.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @lodgement.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lodgements_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lodgement_path(@lodgement), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lodgement_path(@lodgement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>