config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lodgements
  resources :deposits
  resources :withdraws
  resources :bankaccounts
  

root 'bankaccounts#index'

end

app/models/withdraw.rb
class Withdraw < ActiveRecord::Base
	belongs_to :bankaccount
	belongs_to :user
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
  before_action :set_withdraw, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /withdraws
  # GET /withdraws.json
  def index
    @withdraws = Withdraw.all
  end

  # GET /withdraws/1
  # GET /withdraws/1.json
  def show
  end

  # GET /withdraws/new
  def new
    @withdraw = current_user.withdraws.build
  end

  # GET /withdraws/1/edit
  def edit
  end

  # POST /withdraws
  # POST /withdraws.json
  def create
    @withdraw = current_user.withdraws.build(withdraw_params)

    @acc = Bankaccount.find(@withdraw.name)
    @acc.amount -= @withdraw.amount
    @acc.save
    puts @acc.amount



respond_to do |format|
      if @withdraw.save
        format.html { redirect_to @withdraw, notice: 'Withdraw was successfully created.' }
        format.json { render :show, status: :created, location: @withdraw }
      else
        format.html { render :new }
        format.json { render json: @withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /withdraws/1
  # PATCH/PUT /withdraws/1.json
  def update
    respond_to do |format|
      if @withdraw.update(withdraw_params)
        format.html { redirect_to @withdraw, notice: 'Withdraw was successfully updated.' }
        format.json { render :show, status: :ok, location: @withdraw }
      else
        format.html { render :edit }
        format.json { render json: @withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /withdraws/1
  # DELETE /withdraws/1.json
  def destroy
    @withdraw.destroy
    respond_to do |format|
      format.html { redirect_to withdraws_url, notice: 'Withdraw was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdraw
      @withdraw = Withdraw.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdraw_params
      params.require(:withdraw).permit(:name, :amount, :description)
    end
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/withdraws/_form.html.erb
<%= form_for @withdraw, :html => { :class => "form-horizontal withdraw" } do |f| %>

    <% if @withdraw.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@withdraw.errors.count, "error") %> prohibited this withdraw from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @withdraw.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@withdraw[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@withdraw[:amount]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@withdraw[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            withdraws_path, :class => 'btn btn-default' %>

<% end %>

app/views/withdraws/edit.html.erb
<%- model_class = Withdraw -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/withdraws/index.html.erb
<%- model_class = Withdraw -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
<th><%= model_class.human_attribute_name(:email) %></th>
      
<th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @withdraws.each do |withdraw| %>
<%if withdraw.user == current_user %>      


<tr>
        <td><%= link_to withdraw.id, withdraw_path(withdraw) %></td>
        <td><%= withdraw.name %></td>
        <td><%= withdraw.amount %></td>
        <td><%= withdraw.description %></td>
        
 <td><%= withdraw.user.email %></td>
<td><%=l withdraw.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_withdraw_path(withdraw), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      withdraw_path(withdraw),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_withdraw_path,
            :class => 'btn btn-primary' %>

app/views/withdraws/new.html.erb
<%- model_class = Withdraw -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/withdraws/show.html.erb
<%- model_class = Withdraw -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @withdraw.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @withdraw.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @withdraw.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              withdraws_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_withdraw_path(@withdraw), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              withdraw_path(@withdraw),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>